import crypto from 'node:crypto';
import { US } from '../util/time.js';

/**
 * Cac khoi JSON cua file draft CapCut (draft_content.json).
 *
 * Moi moc thoi gian tinh bang micro-giay. CapCut khong cong bo dinh dang nay,
 * nen cau truc o day duoc dung "day du truong" theo dung cac draft that: thieu
 * truong thi CapCut hoac bo qua clip, hoac bao draft loi. Neu ban CapCut cua
 * ban khac, dung `autostory capcut-template` de hoc skeleton tu draft that.
 */

export const newId = () => crypto.randomUUID().toUpperCase();

const FULL_CROP = {
  lower_left_x: 0,
  lower_left_y: 1,
  lower_right_x: 1,
  lower_right_y: 1,
  upper_left_x: 0,
  upper_left_y: 0,
  upper_right_x: 1,
  upper_right_y: 0,
};

export function emptyDraft({ width, height, fps, appVersion = '5.9.0' }) {
  return {
    app_version: appVersion,
    canvas_config: { width, height, ratio: 'original' },
    color_space: 0,
    config: {
      adjust_max_index: 1,
      attachment_info: [],
      combination_max_index: 1,
      export_range: null,
      extract_audio_last_index: 1,
      lyrics_recognition_id: '',
      lyrics_sync: true,
      lyrics_taskinfo: [],
      maintrack_adsorb: true,
      material_save_mode: 0,
      multi_language_current: 'none',
      multi_language_list: [],
      multi_language_main: 'none',
      multi_language_mode: 'none',
      original_sound_last_index: 1,
      record_audio_last_index: 1,
      sticker_max_index: 1,
      subtitle_keywords_config: null,
      subtitle_recognition_id: '',
      subtitle_sync: true,
      subtitle_taskinfo: [],
      system_font_list: [],
      video_mute: false,
      zoom_info_params: null,
    },
    cover: null,
    create_time: 0,
    duration: 0,
    extra_info: null,
    fps,
    free_render_index_mode_on: false,
    group_container: null,
    id: newId(),
    keyframe_graph_list: [],
    keyframes: {
      adjusts: [],
      audios: [],
      effects: [],
      filters: [],
      handwrites: [],
      stickers: [],
      texts: [],
      videos: [],
    },
    last_modified_platform: {
      app_id: 359289,
      app_source: 'cc',
      app_version: appVersion,
      device_id: '',
      hard_disk_id: '',
      mac_address: '',
      os: 'windows',
      os_version: '',
    },
    materials: {
      ai_translates: [],
      audio_balances: [],
      audio_effects: [],
      audio_fades: [],
      audio_track_indexes: [],
      audios: [],
      beats: [],
      canvases: [],
      chromas: [],
      color_curves: [],
      digital_humans: [],
      drafts: [],
      effects: [],
      flowers: [],
      green_screens: [],
      handwrites: [],
      hsl: [],
      images: [],
      log_color_wheels: [],
      loudnesses: [],
      manual_deformations: [],
      masks: [],
      material_animations: [],
      material_colors: [],
      multi_language_refs: [],
      placeholders: [],
      plugin_effects: [],
      primary_color_wheels: [],
      realtime_denoises: [],
      shapes: [],
      smart_crops: [],
      smart_relights: [],
      sound_channel_mappings: [],
      speeds: [],
      stickers: [],
      tail_leaders: [],
      text_templates: [],
      texts: [],
      time_marks: [],
      transitions: [],
      video_effects: [],
      video_trackings: [],
      videos: [],
      vocal_beautifys: [],
      vocal_separations: [],
    },
    mutable_config: null,
    name: '',
    new_version: '110.0.0',
    platform: {
      app_id: 359289,
      app_source: 'cc',
      app_version: appVersion,
      device_id: '',
      hard_disk_id: '',
      mac_address: '',
      os: 'windows',
      os_version: '',
    },
    relationships: [],
    render_index_track_mode_on: true,
    retouch_cover: null,
    source: 'default',
    static_cover_image_path: '',
    time_marks: null,
    tracks: [],
    update_time: 0,
    version: 360000,
  };
}

export function newTrack(type, { flag = 0 } = {}) {
  return { attribute: 0, flag, id: newId(), is_default_name: true, name: '', segments: [], type };
}

export function photoMaterial({ file, width, height, name }) {
  return {
    audio_fade: null,
    cartoon_path: '',
    category_id: '',
    category_name: 'local',
    check_flag: 63487,
    crop: { ...FULL_CROP },
    crop_ratio: 'free',
    crop_scale: 1,
    duration: 10800000000, // anh tinh: CapCut dung 3 gio lam do dai "vo han"
    extra_type_option: 0,
    formula_id: '',
    freeze: null,
    has_audio: false,
    height,
    id: newId(),
    intensifies_audio_path: '',
    intensifies_path: '',
    is_ai_generate_content: false,
    is_copyright: false,
    is_text_edit_overdub: false,
    is_unified_beauty_mode: false,
    local_id: '',
    local_material_id: '',
    material_id: '',
    material_name: name,
    material_url: '',
    matting: { flag: 0, has_use_quick_brush: false, has_use_quick_eraser: false, interactiveTime: [], path: '', strokes: [] },
    media_path: '',
    object_locked: null,
    origin_material_id: '',
    path: file,
    picture_from: 'none',
    picture_set_category_id: '',
    picture_set_category_name: '',
    request_id: '',
    reverse_intensifies_path: '',
    reverse_path: '',
    smart_motion: null,
    source: 0,
    source_platform: 0,
    stable: null,
    team_id: '',
    type: 'photo',
    video_algorithm: {
      algorithms: [],
      complement_frame_config: null,
      deflicker: null,
      gameplay_configs: [],
      motion_blur_config: null,
      noise_reduction: null,
      path: '',
      quality_enhance: null,
      time_range: null,
    },
    width,
  };
}

export function audioMaterial({ file, duration, name }) {
  return {
    app_id: 0,
    category_id: '',
    category_name: 'local',
    check_flag: 1,
    duration: Math.round(duration),
    effect_id: '',
    formula_id: '',
    id: newId(),
    intensifies_path: '',
    is_ai_clone_tone: false,
    is_text_edit_overdub: false,
    is_ugc: false,
    local_material_id: '',
    music_id: '',
    name,
    path: file,
    query: '',
    request_id: '',
    resource_id: '',
    search_id: '',
    source_from: '',
    source_platform: 0,
    team_id: '',
    text_id: '',
    tone_category_id: '',
    tone_category_name: '',
    tone_effect_id: '',
    tone_effect_name: '',
    tone_platform: '',
    tone_second_category_id: '',
    tone_second_category_name: '',
    tone_speaker: '',
    tone_type: '',
    type: 'extract_music',
    video_id: '',
    wave_points: [],
  };
}

export function canvasMaterial() {
  return { album_image: '', blur: 0, color: '', id: newId(), image: '', image_id: '', image_name: '', source_platform: 0, team_id: '', type: 'canvas_color' };
}

export function speedMaterial() {
  return { curve_speed: null, id: newId(), mode: 0, speed: 1, type: 'speed' };
}

export function soundChannelMapping(audio = false) {
  return { audio_channel_mapping: 0, id: newId(), is_config_open: false, type: audio ? 'none' : '' };
}

export function vocalSeparation() {
  return { choice: 0, id: newId(), production_path: '', removed_sounds: [], time_range: null, type: 'vocal_separation' };
}

export function beatsMaterial() {
  return {
    ai_beats: { beat_speed_infos: [], beats_path: '', beats_url: '', melody_path: '', melody_percents: [0], melody_url: '' },
    enable_ai_beats: false,
    gear: 404,
    gear_count: 0,
    id: newId(),
    mode: 404,
    type: 'beats',
    user_beats: [],
    user_delete_ai_beats: null,
  };
}

/** Mot danh sach keyframe cho mot thuoc tinh (scale, position...). */
export function keyframeList(propertyType, points) {
  return {
    id: newId(),
    keyframe_list: points.map((p) => ({
      curveType: 'Line',
      graphID: '',
      id: newId(),
      left_control: { x: 0, y: 0 },
      right_control: { x: 0, y: 0 },
      time_offset: Math.round(p.timeOffsetUs),
      values: [p.value],
    })),
    material_id: '',
    property_type: propertyType,
  };
}

export function videoSegment({ materialId, startUs, durationUs, extraRefs, keyframes = [], renderIndex = 0, clip }) {
  return {
    cartoon: false,
    clip: clip || { alpha: 1, flip: { horizontal: false, vertical: false }, rotation: 0, scale: { x: 1, y: 1 }, transform: { x: 0, y: 0 } },
    color_correct_alg_result: '',
    common_keyframes: keyframes,
    desc: '',
    digital_human_template_group_id: '',
    enable_adjust: true,
    enable_adjust_mask: false,
    enable_color_correct_adjust: false,
    enable_color_curves: true,
    enable_color_match_adjust: false,
    enable_color_wheels: true,
    enable_hsl: false,
    enable_lut: true,
    enable_smart_color_adjust: false,
    enable_video_mask: true,
    extra_material_refs: extraRefs,
    group_id: '',
    hdr_settings: { intensity: 1, mode: 1, nits: 1000 },
    id: newId(),
    intensifies_audio: false,
    is_loop: false,
    is_placeholder: false,
    is_tone_modify: false,
    keyframe_refs: [],
    last_nonzero_volume: 1,
    lyric_keyframes: null,
    material_id: materialId,
    raw_segment_id: '',
    render_index: renderIndex,
    render_timerange: { duration: 0, start: 0 },
    responsive_layout: { enable: false, horizontal_pos_layout: 0, size_layout: 0, target_follow: '', vertical_pos_layout: 0 },
    reverse: false,
    source_timerange: { duration: durationUs, start: 0 },
    speed: 1,
    state: 0,
    target_timerange: { duration: durationUs, start: startUs },
    template_id: '',
    template_scene: 'default',
    track_attribute: 0,
    track_render_index: 0,
    uniform_scale: { on: true, value: 1 },
    visible: true,
    volume: 1,
  };
}

export function audioTrackSegment({ materialId, startUs, durationUs, extraRefs, volume = 1, renderIndex = 0 }) {
  return {
    caption_info: null,
    cartoon: false,
    clip: null,
    color_correct_alg_result: '',
    common_keyframes: [],
    desc: '',
    digital_human_template_group_id: '',
    enable_adjust: false,
    enable_adjust_mask: false,
    enable_color_correct_adjust: false,
    enable_color_curves: true,
    enable_color_match_adjust: false,
    enable_color_wheels: true,
    enable_hsl: false,
    enable_lut: false,
    enable_smart_color_adjust: false,
    enable_video_mask: true,
    extra_material_refs: extraRefs,
    group_id: '',
    hdr_settings: null,
    id: newId(),
    intensifies_audio: false,
    is_loop: false,
    is_placeholder: false,
    is_tone_modify: false,
    keyframe_refs: [],
    last_nonzero_volume: volume,
    lyric_keyframes: null,
    material_id: materialId,
    raw_segment_id: '',
    render_index: renderIndex,
    render_timerange: { duration: 0, start: 0 },
    responsive_layout: { enable: false, horizontal_pos_layout: 0, size_layout: 0, target_follow: '', vertical_pos_layout: 0 },
    reverse: false,
    source_timerange: { duration: durationUs, start: 0 },
    speed: 1,
    state: 0,
    target_timerange: { duration: durationUs, start: startUs },
    template_id: '',
    template_scene: 'default',
    track_attribute: 0,
    track_render_index: 0,
    uniform_scale: null,
    visible: true,
    volume,
  };
}

export function textMaterial({ content, fontSize = 8, color = [1, 1, 1] }) {
  const text = String(content);
  return {
    add_type: 0,
    alignment: 1,
    background_alpha: 1,
    background_color: '',
    background_height: 0.14,
    background_horizontal_offset: 0,
    background_round_radius: 0,
    background_style: 0,
    background_vertical_offset: 0,
    background_width: 0.14,
    base_content: '',
    bold_width: 0,
    border_alpha: 1,
    border_color: '#000000',
    border_width: 0.08,
    caption_template_info: null,
    check_flag: 7,
    combo_info: { text_templates: [] },
    content: JSON.stringify({
      styles: [
        {
          fill: { alpha: 1, content: { render_type: 'solid', solid_color: { alpha: 1, color } } },
          font: { id: '', path: '' },
          range: [0, text.length],
          size: fontSize,
          strokes: [{ content: { render_type: 'solid', solid_color: { alpha: 1, color: [0, 0, 0] } }, width: 0.08 }],
        },
      ],
      text,
    }),
    fixed_height: -1,
    fixed_width: -1,
    font_category_id: '',
    font_category_name: '',
    font_id: '',
    font_name: '',
    font_path: '',
    font_resource_id: '',
    font_size: fontSize,
    font_source_platform: 0,
    font_team_id: '',
    font_title: 'none',
    font_url: '',
    fonts: [],
    force_apply_line_max_width: false,
    global_alpha: 1,
    group_id: '',
    has_shadow: false,
    id: newId(),
    initial_scale: 1,
    inner_padding: -1,
    is_rich_text: false,
    italic_degree: 0,
    ktv_color: '',
    language: '',
    layer_weight: 1,
    letter_spacing: 0,
    line_feed: 1,
    line_max_width: 0.82,
    line_spacing: 0.02,
    multi_language_current: 'none',
    name: '',
    original_size: [],
    preset_category: '',
    preset_category_id: '',
    preset_has_set_alignment: false,
    preset_id: '',
    preset_index: 0,
    preset_name: '',
    recognize_task_id: '',
    recognize_type: 0,
    relevance_segment: [],
    shadow_alpha: 0.8,
    shadow_angle: -45,
    shadow_color: '',
    shadow_distance: 8,
    shadow_point: { x: 1.0182337649086284, y: -1.0182337649086284 },
    shadow_smoothing: 1,
    shape_clip_x: false,
    shape_clip_y: false,
    style_name: '',
    sub_type: 0,
    subtitle_keywords: null,
    subtitle_template_original_fontsize: 0,
    text_alpha: 1,
    text_color: '#FFFFFF',
    text_curve: null,
    text_preset_resource_id: '',
    text_size: 30,
    text_to_audio_ids: [],
    tts_auto_update: false,
    type: 'text',
    typesetting: 0,
    underline: false,
    underline_offset: 0.22,
    underline_width: 0.05,
    use_effect_default_color: true,
    words: { end_time: [], start_time: [], text: [] },
  };
}

export function textSegment({ materialId, startUs, durationUs, extraRefs, renderIndex = 14000, yOffset = -0.72 }) {
  return {
    ...videoSegment({ materialId, startUs, durationUs, extraRefs, renderIndex }),
    clip: {
      alpha: 1,
      flip: { horizontal: false, vertical: false },
      rotation: 0,
      scale: { x: 1, y: 1 },
      transform: { x: 0, y: yOffset },
    },
  };
}

export const HOUR_3_US = 10800000000;
export { US };
